#!/usr/bin/env python3
"""
remediation_report_gen.py — Standalone CARB PDF report generator from Q-Reg ledger.
"""

import argparse
import json
from pathlib import Path
from datetime import datetime, timezone
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.units import inch

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("ledger", type=Path, help="ledger.jsonl path")
    parser.add_argument("--output", type=Path, default=Path("remediation_report.pdf"))
    args = parser.parse_args()

    records = []
    with open(args.ledger, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                records.append(json.loads(line))

    if not records:
        print("No records in ledger.")
        return

    final_root = records[-1].get("running_merkle_root", "N/A")

    doc = SimpleDocTemplate(str(args.output), pagesize=letter,
                            rightMargin=0.75*inch, leftMargin=0.75*inch,
                            topMargin=0.75*inch, bottomMargin=0.75*inch)
    styles = getSampleStyleSheet()
    story = []

    title_style = ParagraphStyle('Title', parent=styles['Heading1'], fontSize=18, spaceAfter=12, alignment=1)
    story.append(Paragraph("Q-Reg Deterministic Compliance Report", title_style))
    story.append(Paragraph("SB 253 / CARB Title 17 CCR Emissions Audit (Standalone)", styles['Heading2']))
    story.append(Spacer(1, 12))

    green = sum(1 for r in records if r.get("computation", {}).get("gate_state") == "GREEN")
    yellow = sum(1 for r in records if r.get("computation", {}).get("gate_state") == "YELLOW")
    black = sum(1 for r in records if r.get("computation", {}).get("gate_state") == "BLACK")

    story.append(Paragraph(f"<b>Summary:</b> {len(records)} facilities | GREEN: {green} | YELLOW: {yellow} | BLACK: {black}", styles['Normal']))
    story.append(Paragraph(f"Final Merkle Root: <font face='Courier'>{final_root}</font>", styles['Normal']))
    story.append(Spacer(1, 12))

    table_data = [["Entity ID", "Gate", "Total MTE", "Citations (truncated)"]]
    for r in records:
        total = r["inputs"].get("scope1_mte", 0) + r["inputs"].get("scope2_mte", 0)
        gate = r.get("computation", {}).get("gate_state", "?")
        cites = "; ".join(r.get("computation", {}).get("policy_citations", [])[:1])
        table_data.append([r["entity_id"], gate, f"{total:.1f}", cites[:50]])

    t = Table(table_data, colWidths=[2*inch, 0.8*inch, 0.9*inch, 3.3*inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a5276')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    story.append(t)

    story.append(Spacer(1, 20))
    story.append(Paragraph("Generated by Q-Reg remediation_report_gen.py | Even The Odds Foundry", styles['Normal']))

    doc.build(story)
    print(f"Report written to {args.output}")

if __name__ == "__main__":
    main()
